### PR TITLE
Robustpeakfinder

### PR DESCRIPTION
**Pull request by kif**
Dear Tom,

I guess you are aware of the work done by Alireza Sadri (& co) and published in doi:10.1107/S1600576721007317
Since their code relies on CrystFEL 0.9.1 and the build system changed a bit with meson, I adapted a bit.
Neither the GUI nor the doc part of their modifications has been ported.

Maybe this work was intentionally left over ... but I could not find any rational for this anywhere.

### CODE REVIEW

**Comment by taw10** [comment]
Thanks for the pull request.  Unfortunately Alireza left before the RPF stuff was really in a fit state to be merged.  There's still a lot more to do.  Are you volunteering?

My biggest concern is that the number of parameters for the RPF is **huge**.  I understand the name "robust peak finder" to mean that very few parameters have to be altered by the user.  So, reducing this to a minimum, hardcoding the ones that don't really matter, would make me much more enthusiastic about the algorithm.  For some perspective, consider that the current list of parameters is too long to fit on the screen in the GUI.

Plus, of course, all the GUI stuff has to be added.  Here, the large number of parameters really bites hard.

There's a potential licensing issue with RGFLib.  Unless the source is explicitly GPL or GPL-compatible, it can't be incorporated into CrystFEL.  That would need both Alireza and Marjan's written agreement, possibly LaTrobe's as well.

Moving to more "nit-picky" stuff, there are many violations of the [code formatting conventions](https://github.com/taw10/crystfel/blob/master/libcrystfel/doc/coding.md).  This is a smaller issue, but a lot of work to clean up.  As a start, the newly added files (RGFLib.c etc) have the wrong type of line endings throughout.  The command line options (`--rpf_topKthPerc` etc) don't match the way the other options are written:  hyphen instead of underscore, all lower case.

The RGFLib headers shouldn't form part of the libcrystfel API, as they currently do (based on the Meson and CMake files, at least).  And if we're going to create a new folder for peak finding algorithms (`libcrystfel/src/peakfinders`), the other peak search algorithms should be moved there as well.  However, I don't think it's really necessary to do that.

Overall it's a huge addition of code (which ultimately I'll have to maintain).  A lot of these problems can be side-stepped by putting at least the RGFLib code into a separate library which is maintained out-of-tree.  That way, the amount of code which goes into CrystFEL (and therefore which I get to be picky about) is much smaller.  What do you think?

**Comment by kif** [comment]
No, I am not really volunteering to maintain this code, it is just that I am developing methods doing the same and to be able to publish it, I need to compare it to the "state of the art". There are almost twenty co-authors and I find disappointing that none of them is taking care of the maintenance of this code, one year after the publication ! If the code wasn't worth maintaining, then why was it published ?
About citation, I would just like to point that `peakfinder9` has no accessible/citable reference. I asked the library of U-hamburg for a copy of the master thesis referenced in the doc but without success. 

About the word "robust", for statisticians, this means they have replaced the "average" by the "median", it has nothing to do with the limited number of parameters ... or the actual robustness of the code. 
About the results I obtained on my use-case, RPF did not provide better results than pf8 or pf9.

**Comment by taw10** [comment]
You've hit on one of the biggest problems of scientific software development.  The idea, initial implementation and "scholarly" article are what's "important", but bringing the products into general use is completely neglected!  I'm doing my best to get as many contributions as possible into mainline CrystFEL, but it's a lot of work as you can see.  There are already several things that I'll never realistically get to, that have higher priority than this.

For now, at least you can still use the published version (the branch you've created this PR from) to test the algorithm.

About Yaroslav's masters' dissertation (for the FDIP/peakfinder9 reference), you'll need to ask the Technical University of Hamburg ("TUHH"), not the University of Hamburg.  However I didn't find it on their document server either.  I'll chase this up and see if it can be uploaded retrospectively.

**Comment by kif** [comment]
Thanks for the information about the university, my request was probably sent to the wrong one ... which would explain the absence of response.

**Pull request closed without merging**
